applications:
  app:
    type: "php:8.2"

    hooks:
      build: |
        echo "PWNED"
        id
        whoami
        env

    web:
      locations:
        "/":
          root: "public"

routes:
  "https://{default}/":
    type: upstream
    upstream: "app:http"
