applications:
  app:
    type: "php:8.2"

    web:
      locations:
        "/":
          root: "public"
          index:
            - index.php

routes:
  "https://{default}/":
    type: upstream
    upstream: "app:http"
